PRAGMA table_info(PRODUCT); --VERIFICANDO INFORMÇÕES DE TABELAS(NOME E TIPOS DE DADOS);
SELECT * FROM PRODUCT; -- RECUPERANDO INFORMAÇÕES DA TABELA PRODUCT;
SELECT PRODUCT_ID, DESCRIPTION, PRICE, round(PRICE * 1.25, 2) AS TAXED_PRICE_25 FROM PRODUCT; -- CONSULTA NA TABELA PRODUCT E CRIAÇÃO DE COLUNA COM PREÇO ADICIONANDO 25% AO VALOR ATUAL TAMBÉM UTILIZAMOS A FUNÇÃO ROUND PARA DEFINIR AS CASAS DECIMAIS;
SELECT PRODUCT_ID, DESCRIPTION, PRICE AS UNTAXED_PRICE, round(PRICE * 1.25, 2) AS TAXED_PRICE_25 FROM PRODUCT; -- RENOMEANDO A COLUNA PRICE PARA UNTAXED_PRICE;
SELECT ORDER_ID, CUSTOMER_ID, ORDER_QTY FROM CUSTOMER_ORDER WHERE ORDER_QTY; --VERIFICANDO QUANTIDADE DE PEDIDOS 
--TEMOS TRÊS PEDIDOS PARA OS CLIENTES DE ID 03 UM PEDIDO PARA O CLIENTE DE ID 1 E UM PEDIDO PARA O CLIENTE DE ID 5

SELECT ORDER_ID, CUSTOMER_ID, ORDER_QTY FROM CUSTOMER_ORDER WHERE ORDER_QTY > 400; --VERIFICANDO PEDIDOS COM QUATIDADE SUPERIOR A 400
--TEMOS UM PEDIDO PARA O CLIENTE DE ID 01 E DOIS PEDIDOS PARA O CLIENTE DE ID 03 TODOS SUPERIORES A 400

SELECT NAME, CITY || ', ' || STATE AS LOCATION FROM CUSTOMER; --CONCAQUETANAÇÃO DE TEXTO
SELECT CUSTOMER_ID, NAME, CITY, STATE FROM CUSTOMER WHERE STATE = 'TX'; --VERIFICANDO CLIENTES DO ESTADO DE TEXAS
SELECT CUSTOMER_ID, NAME, CITY, STATE FROM CUSTOMER WHERE STATE != 'TX'; --VERIFICANDO CLIENTES QUE NÃO SÃO DO ESTADO DE TEXAS


SELECT NAME, SUM(ORDER_QTY * PRICE) AS REVENUE FROM CUSTOMER INNER JOIN CUSTOMER_ORDER ON CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID INNER JOIN PRODUCT ON PRODUCT.PRODUCT_ID = CUSTOMER_ORDER.PRODUCT_ID GROUP BY NAME -- PUXANDO INFORMAÇÕES DE TOTAIS DE VENDAS E AGRUPANDO POR CLIENTES.

